### ISSUE TITLE
一个问题和一个建议

### ISSUE THREAD

**Issue by atfa** [xuexiangjys/flutter_template#1]
作者辛苦了。

1、请问i18n是用哪个插件完成的？能不能添加一下增加语言、增加翻译后如果生成更新文件？

2、建议再出一个增强版。新项目一般都还需要 相机、定位、扫码、指纹 这四个权限，如果能增加到增强版中去，配置好Android和iOS的插件权限，这个项目一定大货喜欢。

**Comment by xuexiangjys** [comment]
其一:国际化用的是vscode提供的插件 [vscode-flutter-i18n-json](https://marketplace.visualstudio.com/items?itemName=esskar.vscode-flutter-i18n-json)
具体怎么使用你还是自己去看文档吧
其二:这个可以考虑,但是还是需要等flutter的生态再成熟一点,目前尚未发现比较好的三方库可以使用,自己写太费时了
