### ISSUE TITLE
登录页面按返回键无法退出app

### ISSUE THREAD

**Issue by ff-frida** [xuexiangjys/flutter_template#10]
最新版本。
同意协议之后，进入登录页面。点击返回键无法退出app

**Comment by xuexiangjys** [comment]
功能就是这么写的,不喜欢你可以自己去掉啊...

**Comment by ff-frida** [comment]
> 功能就是这么写的,这是模板而言,不喜欢你可以自己去掉啊...

不好意思，我以为是bug...
