### ISSUE TITLE
在 Flutter 2.0.1 环境中运行，会有异常，看起来是语法的不兼容

### ISSUE THREAD

**Issue by Jmysy** [xuexiangjys/flutter_template#11]
/D:/service/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_image-1.6.0/lib/src/extended_image.dart:785:44: Error: No named parameter with the name 'nullOk'.
    _invertColors = MediaQuery.of(context, nullOk: true)?.invertColors ??
                                           ^^^^^^
/D:/service/flutter/packages/flutter/lib/src/widgets/media_query.dart:818:25: Context: Found this candidate, but the arguments don't match.
  static MediaQueryData of(BuildContext context) {

**Comment by purgeyao** [comment]
+1

**Comment by xuexiangjys** [comment]
extended_image: ^1.5.0  ->  extended_image: 1.5.0

**Comment by xuexiangjys** [comment]
> 你的意思是 extended 这个依赖的自动小版本升级造成了依赖冲突，是这样吗

对啊,一般这种升级api接口变的,应该升大版本的

**Comment by Jmysy** [comment]
降低以来版本后，仍存在该问题

**Comment by xuexiangjys** [comment]
> 固定依赖版本，仍存在该问题

那你自己去插件的官方地址找解决方案啊...
https://github.com/fluttercandies/extended_image

**Comment by xuexiangjys** [comment]
升级到最新的版本3.0.0

**Comment by Jmysy** [comment]
修改 image 3.0.0 后产生一连串的强制依赖，和依赖版本的冲突

**Comment by xuexiangjys** [comment]
> 希望可以出一个兼容 flutter 2.0.0 的分支，可打赏或红包 ，因刚入门，多数地方使不上劲

我找个时间升级一下吧,维护升级这东西挺费劲的

**Comment by Jmysy** [comment]
> > 希望可以出一个兼容flutter 2.0.0的分支，可打赏或红包，因刚入门，多个地方使不上劲
> 
> 我找个时间升级一下吧，维护升级这东西挺费劲的

理解理解，我也是一名开源作者，Flutter 临时工作需要，这周刚刚接触，这是我的开源社区 https://gitee.com/pear-admin , 有问题随时沟通
