### ISSUE TITLE
auto_route生成的代码会出现语法错误

### ISSUE THREAD

**Issue by cn1001wang** [xuexiangjys/flutter_template#13]
![image](https://user-images.githubusercontent.com/34416681/111024042-78c19980-8417-11eb-9ee8-6a9b6fc2550b.png)

引入 getTransitions的时候 前面会比示例中多一个点。
我是克隆的2.0分支

命令是 `flutter packages pub run build_runner watch --delete-conflicting-outputs` 和 `flutter packages pub run build_runner build` 两个效果是一样的都多一个点

**Comment by xuexiangjys** [comment]
升级到^1.0.0-beta.10试试看,flutter2.0更新的太多,前天还没看到auto_route有更新

**Comment by xuexiangjys** [comment]
我试过了,并没有出现任何问题

**Comment by cn1001wang** [comment]
我重新下一个他又好了

**Comment by cn1001wang** [comment]
auto_route 升级到1.0.0改动好大啊
