### ISSUE TITLE
No named parameter with the name 'nullOk'.

### ISSUE THREAD

**Issue by panw3i** [xuexiangjys/flutter_template#16]
Launching lib/main.dart on macOS in debug mode...
lib/main.dart:1
../.pub-cache/hosted/pub.flutter-io.cn/extended_image-1.6.0/lib/src/extended_image.dart:785:44: Error: No named parameter with the name 'nullOk'.
    _invertColors = MediaQuery.of(context, nullOk: true)?.invertColors ??
                                           ^^^^^^
../flutter/packages/flutter/lib/src/widgets/media_query.dart:818:25: Context: Found this candidate, but the arguments don't match.
  static MediaQueryData of(BuildContext context) {
                        ^^

Command PhaseScriptExecution failed with a nonzero exit code

note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
** BUILD FAILED **

Exception: Build process failed
Exited (sigterm)

**Comment by kexiaoderenren** [comment]
你好，我也遇到相同的问题，请问有啥解决方式吗？(hello,i have the same problems,did you solve it?)

**Comment by Leadrive** [comment]
打开这个文件，删除nullOk就可以。

**Comment by xuexiangjys** [comment]
flutter2.0的问题,更新一下项目代码就可以了
