### ISSUE TITLE
项目启动时遇到的一个问题

### ISSUE THREAD

**Issue by British-shorthair** [xuexiangjys/flutter_template#18]
运行flutter run 时，报错信息如下

fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.

请问您有遇到过类似的情况吗？有的话麻烦和我说一下解决办法，谢谢

**Comment by xuexiangjys** [comment]
没有,你还是把flutter的环境先安装好再说吧
