### ISSUE TITLE
打包失败了 怎么解决？

### ISSUE THREAD

**Issue by justb** [xuexiangjys/flutter_template#21]
![image](https://user-images.githubusercontent.com/22002343/117937271-5de8a400-b338-11eb-9afc-0a0f1fcbd3a6.png)

![image](https://user-images.githubusercontent.com/22002343/117937000-182bdb80-b338-11eb-9710-218ba184a868.png)

**Comment by xuexiangjys** [comment]
这种问题, 你自己去问google,别来问我,谢谢

**Comment by justb** [comment]
问的是社区 就问你一个人吗？
