### ISSUE TITLE
是否考虑默认集成小程序引擎uni SDK

### ISSUE THREAD

**Issue by trainliang** [xuexiangjys/flutter_template#25]
uniSDK地址参考：
https://nativesupport.dcloud.net.cn/README

后端方案：JAP+授权登录
https://gitee.com/fujieid/jap-ids-demo/issues/I3YQ8Z

**Comment by xuexiangjys** [comment]
为什么要集成uni?

**Comment by trainliang** [comment]
总结了三点：
1.方便历史程序模块迁入，开发APP前有做过小程序或应用，开发的app想直接引用，uniSDk可直接转换后部署使用
2.方便自有平台搭建，模块化应用管理，框架搭建后，flutter只搭建出外部UI模板就可以，应用或功能可以不限制UI，使用现有的小程序UI，或云函数开发，上边我提供的授权方式可解耦模块，或者部分功能对外服务直接上架微信支付宝小程序不需要二开三开
3.三方应用的接入的标准化交付，对别的项目（外包或多团队开发）开发可统一交付方式，减少接入成本
