### ISSUE TITLE
启动报错，请帮忙看看什么原因

### ISSUE THREAD

**Issue by tcjsg** [xuexiangjys/flutter_template#26]
<img width="311" alt="图片" src="https://user-images.githubusercontent.com/50619223/125204624-bbee2500-e2b0-11eb-9bdc-a1e5414cffb1.png">
<img width="898" alt="图片" src="https://user-images.githubusercontent.com/50619223/125204658-e50eb580-e2b0-11eb-8aa3-347e52a98630.png">
老师，你好，能帮忙看看什么问题吗？

**Comment by xuexiangjys** [comment]
已修复
4252d563394dec09cb0c216f0f34745f0ee8a673
