### ISSUE TITLE
The plugins `flutter_webview_plugin, image_picker_saver` use a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by MeiChao** [xuexiangjys/flutter_template#32]
The plugins `flutter_webview_plugin, image_picker_saver` use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by xuexiangjys** [comment]
推荐使用flutter 2.0.6版本
