### ISSUE TITLE
报错需要migrate this app to the V2 embedding

### ISSUE THREAD

**Issue by jiashaoying** [xuexiangjys/flutter_template#33]
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
━━━━━━━━━━━━━━━━━━
Warning
────────────────────────────────────────────────────────────
──────────────────
Your Flutter application is created using an older version
of the Android
embedding. It is being deprecated in favor of Android
embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project. You may also pass the
--ignore-deprecation flag to
ignore this check and continue with the deprecated v1
embedding. However,
the v1 Android embedding will be removed in future versions
of Flutter.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
━━━━━━━━━━━━━━━━━━
The detected reason was:

  /Users/jiashaoying/github_projects/flutter_template/androi
  d/app/src/main/AndroidManifest.xml uses
  `android:name="io.flutter.app.FutterApplication"`
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
━━━━━━━━━━━━━━━━━━

Running "flutter pub get" in flutter_template...                    5.1s
This app is using a deprecated version of the Android
embedding.
To avoid unexpected runtime failures, or future build
failures, try to migrate this app to the V2 embedding.
Take a look at the docs for migrating an app:
https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-A
ndroid-projects
The plugin `package_info_plus` requires your app to be
migrated to the Android embedding v2. Follow the steps on
https://flutter.dev/go/android-project-migration and re-run
this command.

**Comment by xuexiangjys** [comment]
推荐使用flutter 2.0.6版本
