### ISSUE TITLE
lib/init/default_app.dart GlobalEasyRefreshLocalizations.delegate 抛错

### ISSUE THREAD

**Issue by zkeyword** [xuexiangjys/flutter_template#4]
lib/init/default_app.dart GlobalEasyRefreshLocalizations.delegate 抛错，提示不存在

```
environment:
  sdk: ">=2.7.0 <3.0.0"
```

**Comment by xuexiangjys** [comment]
你应该是把flutter_easyrefresh这个框架升级到最新的版本了.这个库的最新版本是没有默认国际化设置的,也就是GlobalEasyRefreshLocalizations.delegate, 请自己做适配,或者降回2.1.1版本
