### ISSUE TITLE
Support flutter_easyrefresh

### ISSUE THREAD

**Issue by Mister-Hope** [xuexiangjys/flutter_template#6]
The newest flutter_easyrefresh drop i18n suppport, and I am not familar with the i18n support.

So could you please support it? Thanks
![image](https://user-images.githubusercontent.com/33315834/97874322-cb959100-1d53-11eb-9721-14bca18506a5.png)

**Comment by xuexiangjys** [comment]
我挑个时间更新一下,  跨平台最麻烦的就是升级问题.每次升级都是一堆坑

**Comment by xuexiangjys** [comment]
由于本模板不使用classicalHeader,因此暂不做兼容,只是升级一下版本库
